# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favor',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=32)),
                ('url', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=50)),
                ('favor_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SendMsg',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('email', models.CharField(db_index=True, max_length=32)),
                ('times', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('ctime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.NewsType'),
        ),
        migrations.AddField(
            model_name='news',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
        migrations.AddField(
            model_name='favor',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.News'),
        ),
        migrations.AddField(
            model_name='favor',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='favor',
            unique_together=set([('user_info', 'news')]),
        ),
    ]
