# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('ctime', models.DateTimeField()),
                ('device', models.CharField(max_length=16)),
                ('content', models.CharField(max_length=150)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.News')),
                ('reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='web.Comment')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserInfo')),
            ],
        ),
    ]
